# Generated by Django 4.2 on 2023-04-24 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'departamento',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id_profesor', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10, unique=True)),
                ('id_departamento_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcialDjago.departamento')),
            ],
            options={
                'db_table': 'profesor',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('nivel', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
                ('id_profesor_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcialDjago.profesor')),
            ],
            options={
                'db_table': 'curso',
            },
        ),
    ]
